export { default as AboutUs } from './AboutUs'
export { default as Base } from './Base'
export { default as Post } from './Post'
export { default as Posts } from './Posts'
export { default as Contacts } from './Contacts'
export { default as Home } from './Home'
